// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkK7tDuZU56DIc7mlo7Dv-451Idf51608',
    appId: '1:1066544431393:android:82bb6bc259c5aadec97e60',
    messagingSenderId: '1066544431393',
    projectId: 'klink-b0358',
    storageBucket: 'klink-b0358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDPKKPijW81wPAga8sXolBfVwLsc9W-0',
    appId: '1:1066544431393:ios:e23758cc583ec8c3c97e60',
    messagingSenderId: '1066544431393',
    projectId: 'klink-b0358',
    storageBucket: 'klink-b0358.firebasestorage.app',
    iosBundleId: 'com.universaldist.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvdqpQtsYkxhZbMujdPsLzs_OR7ppW34',
    appId: '1:320969644964:web:2abeaa7ad0f62a9b363f31',
    messagingSenderId: '320969644964',
    projectId: 'arious-4a07f',
    authDomain: 'arious-4a07f.firebaseapp.com',
    storageBucket: 'arious-4a07f.firebasestorage.app',
    measurementId: 'G-2EEXBYWQCC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDPKKPijW81wPAga8sXolBfVwLsc9W-0',
    appId: '1:1066544431393:ios:e23758cc583ec8c3c97e60',
    messagingSenderId: '1066544431393',
    projectId: 'klink-b0358',
    storageBucket: 'klink-b0358.firebasestorage.app',
    iosBundleId: 'com.universaldist.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXvdqpQtsYkxhZbMujdPsLzs_OR7ppW34',
    appId: '1:320969644964:web:edacf6a8c2a0991b363f31',
    messagingSenderId: '320969644964',
    projectId: 'arious-4a07f',
    authDomain: 'arious-4a07f.firebaseapp.com',
    storageBucket: 'arious-4a07f.firebasestorage.app',
    measurementId: 'G-KXBW19P01M',
  );
}
